#!/system/bin/sh
# An unforunate wrapper script 
# so that the exit code of pppd may be retrieved


#PPPD_PID=""
PPPD_EXIT=""

/system/bin/setprop "net.gprs.ppp-exit" ""

/system/bin/log -t pppd "Starting pppd"

U=`/system/bin/getprop "net.ppp0.user"`
P=`/system/bin/getprop "net.ppp0.pass"`

/system/bin/logwrapper /system/bin/pppd ttyACM0 115200 nodetach noauth noipdefault defaultroute usepeerdns user "$U" password "$P" connect "chat -v '' AT OK ATD*99# CONNECT" debug
/system/bin/logwrapper /system/bin/pppd ttyACM1 115200 nodetach noauth noipdefault defaultroute usepeerdns user "$U" password "$P" connect "chat -v '' AT OK ATD*99# CONNECT" debug

PPPD_EXIT=$?
#PPPD_PID=$!

#/system/bin/log -t pppd "pppd pid: $PPPD_PID"
/system/bin/log -t pppd "pppd exited with $PPPD_EXIT"

/system/bin/setprop "net.gprs.ppp-exit" "$PPPD_EXIT"
